Add support for Laravel 7 + PHP 7.4
laravel-notification-channels/webhook pull request #34
Opened 2020-03-03 09:36 UTC by Okipa

Hi there, here is my implementation proposal for :

* Laravel 7 support addition.
* PHP 7.4 support addition.
* PHP 7.0 support drop.

2020-03-07 01:28 UTC, atymic requested changes

2020-03-07 01:28 UTC, atymic commented on composer.json
> +        "php": "^7.1",
```suggestion
        "php": "^7.2",
```

2020-03-07 01:28 UTC, atymic commented on composer.json
> +        "illuminate/support": "~5.8.0||^6.0||^7.0"
This should match the `illuminate/notifications` package

2020-03-07 01:28 UTC, atymic commented on composer.json
> +        "phpunit/phpunit": "^7.0||^8.0",
Just drop 7.0 :)

2020-03-07 01:28 UTC, atymic commented on composer.json
> +        "mockery/mockery": "^0.9.5||^1.0",
Also drop 0.x here

2020-03-08 20:29 UTC, atymic commented
@Okipa can you make the above changes please? :)

2020-03-08 22:33 UTC, atymic commented
Closing in favour of #35, thanks for the PR though :)

2020-03-08 22:33 UTC, closed without merging

2020-03-09 18:23 UTC, Okipa commented
Hey @atymic, sorry for the delay, I’m on vacations abroad and I’m trying to disconnect as much as I can.
Just saw you released the new tag with the Laravel 7 compatibility, thanks !

2020-03-09 21:34 UTC, atymic commented
No worries :) 

All good, glad you had a good weekend!